config/routes.rb
StoreInventory::Application.routes.draw do

  resources :indents

  resources :store_items

  resources :store_categories

  resources :store_types

  resources :stores

   root :to => 'welcome#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  attr_accessible :code, :name
  has_many :indents
  has_many :store_items
#  validates :name, :length => { :minimum => 2, :maximum => 30 }, presence: true
#  validates :code, :length => { :minimum => 2, :maximum => 10 }, presence: true

  validates_length_of     :name, :within => 1..20
#  validates_uniqueness_of :code
  validates_length_of     :code, :within => 1..10
end

app/models/store_type.rb
class StoreType < ActiveRecord::Base
  attr_accessible :code, :name
  has_many :store_items
  validates_length_of     :name, :within => 1..20
  validates_uniqueness_of :code
  validates_length_of     :code, :within => 1..10
  validates_presence_of   :name,:code
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController


  def index
    @stores = Store.all
     @store = Store.new

  end


  def edit
    @store = Store.find(params[:id])
   respond_to do |format|
      format.html { redirect_to stores_url }
      format.js
    end
  end

  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      @store.save
        format.html { redirect_to stores_url, notice: 'Store was successfully created.' }
        format.js
    end
  end

 def update
    @store = Store.find(params[:id])

    respond_to do |format|
      @store.update_attributes(params[:store])
        format.html { redirect_to stores_url, notice: 'Store was successfully updated.' }
        format.js 
    end
  end


  def destroy
    @store = Store.find(params[:id])
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.js
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for @store, :html => { :class => 'form-horizontal' }, :remote => true do |f| %>
<%= render 'shared/error_msg', object: f.object %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<tr   id="<%= dom_id store %>">
        <td><%= link_to store.id, store_path(store) %></td>
        <td><%= store.name %></td>
        <td><%= store.code %></td>
        <td><%=l store.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_path(store), :class => 'btn btn-mini', :remote => true %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_path(store),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger', :remote => true %>
        </td>
      </tr>

app/views/stores/create.js.erb
$('<%= j render @store %>').appendTo('#stores').hide().fadeIn();
$("#new_store")[0].reset();

app/views/stores/destroy.js.erb
$("#<%= dom_id @store %>").remove();

app/views/stores/edit.js.erb
$("#new_store").replaceWith("<%= j render "form" %>");

app/views/stores/index.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<table class="table table-bordered" id="stores" >
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <%= render store %>
    <% end %>
  </tbody>
</table>

<%#= link_to t('.new', :default => t("helpers.links.new")),
            new_store_path,
            :class => 'btn btn-primary' %>
<div id="ffor" >
<%= render :partial => 'form' %>
</div>

app/views/stores/update.js.erb
$("#store_<%= @store.id %>").replaceWith("<%= j render @store %>");
// reset for new form
<% aa = @store.id%>
<% @store = Store.new %>
$("#edit_store_<%= aa %>").replaceWith("<%= j render 'form'  %>");
$("#new_store")[0].reset();