config/routes.rb
StoreInventory::Application.routes.draw do

  resources :indents

  resources :store_items

  resources :store_categories

  resources :store_types

  resources :stores

   root :to => 'welcome#index'

end

app/models/store_category.rb
class StoreCategory < ActiveRecord::Base
  attr_accessible :code, :name
  validates_length_of     :name, :within => 1..20
  validates_uniqueness_of :code
  validates_length_of     :code, :within => 1..10
  validates_presence_of:name,:code
end

app/controllers/store_categories_controller.rb
class StoreCategoriesController < ApplicationController

  def index
    @store_categories = StoreCategory.all
    @store_category = StoreCategory.new
    respond_to do |format|
      format.html 
      format.js
    end
  end
 
 
  def edit
    @store_category = StoreCategory.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  def create
    @store_category = StoreCategory.new(params[:store_category])

    respond_to do |format|
      if @store_category.save
        format.html { redirect_to store_categories_url, notice: 'Store category was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end
  def update
    @store_category = StoreCategory.find(params[:id])

    respond_to do |format|
      if @store_category.update_attributes(params[:store_category])
        format.html { redirect_to store_categories_url, notice: 'Store category was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js
      end
    end
  end
  def destroy
    @store_category = StoreCategory.find(params[:id])
    @store_category.destroy

    respond_to do |format|
      format.html { redirect_to store_categories_url }
      format.js
    end
  end
end

app/helpers/store_categories_helper.rb
module StoreCategoriesHelper
end

app/views/store_categories/_form.html.erb
<%= form_for @store_category, :html => { :class => 'form-horizontal' }, :remote => true do |f| %>
<%= render 'shared/error_msg', object: f.object %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                store_categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/store_categories/_store_category.html.erb
<tr id="<%= dom_id store_category %>">
        <td><%= link_to store_category.id, store_category_path(store_category) %></td>
        <td><%= store_category.name %></td>
        <td><%= store_category.code %></td>
        <td><%=l store_category.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_category_path(store_category), :class => 'btn btn-mini', :remote=> true %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_category_path(store_category),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger', :remote => true %>
        </td>
      </tr>

app/views/store_categories/create.js.erb
$('<%= j render @store_category %>').appendTo('#store_category').hide().fadeIn();
$("#new_store_category")[0].reset();

app/views/store_categories/destroy.js.erb
$("#<%= dom_id @store_category %>").remove();

app/views/store_categories/edit.html.erb
<%- model_class = StoreCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/store_categories/edit.js.erb
$("#new_store_category").replaceWith("<%= j render "form" %>");

app/views/store_categories/index.html.erb
<%- model_class = StoreCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-bordered" id="store_category">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @store_categories.each do |store_category| %>
      <%= render store_category %>
    <% end %>
  </tbody>
</table>


<div id="ffor" >
<%= render :partial => 'form' %>
</div>

app/views/store_categories/new.html.erb
<%- model_class = StoreCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/store_categories/show.html.erb
<%- model_class = StoreCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @store_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @store_category.code %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              store_categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_category_path(@store_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_category_path(@store_category),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/store_categories/update.js.erb
$("#store_category_<%= @store_category.id %>").replaceWith("<%= j render @store_category %>");
// reset for new form
<% aa = @store_category.id%>
<% @store_category = StoreCategory.new %>
$("#edit_store_category_<%= aa %>").replaceWith("<%= j render 'form'  %>");
$("#new_store_category")[0].reset();