config/routes.rb
StoreInventory::Application.routes.draw do

  resources :indents

  resources :store_items

  resources :store_categories

  resources :store_types

  resources :stores

   root :to => 'welcome#index'

end

app/models/indent.rb
class Indent < ActiveRecord::Base
  attr_accessible :description, :indent_no, :name, :store_id, :indent_items_attributes
  has_many :indent_items
  accepts_nested_attributes_for :indent_items, :allow_destroy=> true
  belongs_to:store
  validates :name, :length => { :minimum => 2, :maximum => 30 }, :presence =>true
  validates :description, :length => { :minimum => 2, :maximum => 60 }, :presence=> true
  validates :indent_no, :presence=> true, :numericality => true
  validates :store_id, :presence=> true, :numericality => true

  def store_name
    store.name unless store.nil?
  end

end

app/controllers/indents_controller.rb
class IndentsController < ApplicationController
 
  def index
    @indents = Indent.all

  end

  def show
    @indent = Indent.find(params[:id],:include=> :indent_items)

  end

  def new
    @indent = Indent.new
    2.times { @indent.indent_items.build }
   
  end

 
  def edit
    @indent = Indent.find(params[:id])
  end

 
  def create
    @indent = Indent.new(params[:indent])

    respond_to do |format|
      if @indent.save
        format.html { redirect_to @indent, notice: 'Indent was successfully created.' }
        format.json { render json: @indent, status: :created, location: @indent }
      else
        format.html { render action: "new" }
        format.json { render json: @indent.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @indent = Indent.find(params[:id])

    respond_to do |format|
      if @indent.update_attributes(params[:indent])
        format.html { redirect_to @indent, notice: 'Indent was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @indent.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @indent = Indent.find(params[:id])
    @indent.destroy
  end
end

app/helpers/indents_helper.rb
module IndentsHelper
end

app/views/indents/_form.html.erb
<%= form_for @indent, :html => { :class => 'form-horizontal' } do |f| %>
<%= render 'shared/error_msg', object: f.object %>
 <% if indent = Indent.last %>
  <div class="control-group">
    <%= f.label :indent_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :indent_no, :class => 'number_field' , :value => indent.indent_no.next %>
    </div>
  </div>
<% else  %>
  <div class="control-group">
    <%= f.label :indent_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :indent_no, :class => 'number_field' %>
    </div>
  </div>
<% end  %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :store_id, :class => 'control-label' %>
    <div class="controls">
 <%= collection_select(:indent, :store_id, Store.order(:name), :id, :name,  :prompt => "Select Store") %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' , :size => '5x5' %>
    </div>
  </div>

<%= f.fields_for :indent_items do |ff| %>

<%= render 'indent_item_fields', f: ff %>
<% end %>
 <%= link_to_add_fields "Add Items ", f, :indent_items %>
</ br>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                indents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/indents/_indent_item_fields.html.erb
<fieldset>
<table>
<tr>

<td id='indent_item'><%= f.grouped_collection_select(:store_item_id, Store.order(:name),:store_items,:name, :id, :name, {:prompt => "Select store items"}, {:class => "indent_item"})%></td>
<td><%= f.text_field :issued, :class => 'input-medium', :placeholder =>"Issued Type" %></td>
<%#= f.text_field :quantity, :class => 'input-small', :placeholder =>"Qunatity" %>
<td><%= f.text_field :price, :class => 'input-small', :placeholder =>"Price" %></td>
<td><%= f.text_field :pending, :class => 'input-small', :placeholder =>"Pending" %></td>
<td><%= f.text_field :issued, :class => 'input-small', :placeholder =>"Issued " %></td>
<td><%= f.text_field :required, :class => 'input-small', :placeholder =>"Required" %></td>
<%= f.hidden_field :_destroy %>
<td><%= link_to "remove", '#', :class => "remove_fields" %></td>
</tr>
</table>
</fieldset>

app/views/indents/edit.html.erb
<%- model_class = Indent -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/indents/index.html.erb
<%- model_class = Indent -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-bordered ">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:indent_no) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:store_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @indents.each do |indent| %>
      <tr>
        <td><%= link_to indent.id, indent_path(indent) %></td>
        <td><%= indent.indent_no %></td>
        <td><%= indent.name %></td>
        <td><%= indent.store_name %></td>
        <td><%= indent.description %></td>
        <td><%=l indent.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_indent_path(indent), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      indent_path(indent),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to t('.new', :default => t("helpers.links.new")),
            new_indent_path,
            :class => 'btn btn-primary' %>

app/views/indents/new.html.erb
<%- model_class = Indent -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/indents/show.html.erb
<%- model_class = @indent.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => "Indent"%></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong> Name :</strong></dt>
  <dd><%= @indent.name %></dd>
  <dt><strong>Indent No :</strong></dt>
  <dd><%= @indent.indent_no %></dd>

  <dt><strong>Description:</strong></dt>
  <dd><%= @indent.description %></dd>
  <dt><strong>Store:</strong></dt>
  <dd><%= @indent.store_name %></dd>
</dl>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Item name</th>
      <th>Issued </th>
      <th>Issued</th>
      <th>Required</th>
      <th>Pending</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>

<% @indent.indent_items.each do |item| %>
<tr>
<td><%= item.store_item_name %></td>
<td><%= item.issued %></td>
<td><%= item.issued %></td>
<td><%= item.required %></td>
<td><%= item.pending %></td>
<td><%= item.price %></td>
<% end %>
</tr>
</tbody>
</table>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              indents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_indent_path(@indent), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              indent_path(@indent),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>