config/routes.rb
StoreInventory::Application.routes.draw do

  resources :indents

  resources :store_items

  resources :store_categories

  resources :store_types

  resources :stores

   root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<!--
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<header class="jumbotron subhead">
  <div class="container">
    <h1>JavaScript for Bootstrap</h1>
    <p class="lead">Bring Bootstrap's components to life&mdash;now with 13 custom jQuery plugins.
  </div>
</header>
-->
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">Some Store</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Store" , stores_path %></li>
            <li><%= link_to "Store Type", store_types_path %></li>
            <li><%= link_to "Store Category", store_categories_path %></li>
            <li><%= link_to "Store Item ", store_items_path  %></li>
            <li><%= link_to "Indent", indents_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
<% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">×</a>
        <%= msg %>
      </div>
    <% end %>
    <div class="row">
      <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2>About Us</h2>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </div>
    </div>
  </div>
<hr>
<footer class="footer">
      <div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>Designed and built with all the love in the world </p>

      </div>
    </footer>

</body>


</html>